### ISSUE TITLE
ValueError: bad typecode in array for tdsTypeTimeStamp

### ISSUE THREAD

**Issue by gsainsbury86** [petebachant/pyTDMS#2]
Hi,

I am in the process of migrating a web application from one webserver to another and I'm hitting a bit of a problem. The application is written in Python 3.4 and Flask and was originally hosted with the Flask development server but I've rolled it out to httpd on Redhat.

When I try and read one of our TDMS files, I get the following error:

```
    [Tue Sep 20 15:53:25.431681 2016] [wsgi:error] [pid 21070] ERROR:tpa_tools:Exception on /beehive/get_data [POST]
    [Tue Sep 20 15:53:25.431698 2016] [wsgi:error] [pid 21070] Traceback (most recent call last):
    [Tue Sep 20 15:53:25.431704 2016] [wsgi:error] [pid 21070]   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app
    [Tue Sep 20 15:53:25.431709 2016] [wsgi:error] [pid 21070]     response = self.full_dispatch_request()
    [Tue Sep 20 15:53:25.431715 2016] [wsgi:error] [pid 21070]   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1641, in full_dispatch_request
    [Tue Sep 20 15:53:25.431725 2016] [wsgi:error] [pid 21070]     rv = self.handle_user_exception(e)
    [Tue Sep 20 15:53:25.431733 2016] [wsgi:error] [pid 21070]   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1544, in handle_user_exception
    [Tue Sep 20 15:53:25.431740 2016] [wsgi:error] [pid 21070]     reraise(exc_type, exc_value, tb)
    [Tue Sep 20 15:53:25.431748 2016] [wsgi:error] [pid 21070]   File "/usr/local/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    [Tue Sep 20 15:53:25.431757 2016] [wsgi:error] [pid 21070]     raise value
    [Tue Sep 20 15:53:25.431765 2016] [wsgi:error] [pid 21070]   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1639, in full_dispatch_request
    [Tue Sep 20 15:53:25.431773 2016] [wsgi:error] [pid 21070]     rv = self.dispatch_request()
    [Tue Sep 20 15:53:25.431780 2016] [wsgi:error] [pid 21070]   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1625, in dispatch_request
    [Tue Sep 20 15:53:25.431790 2016] [wsgi:error] [pid 21070]     return self.view_functions[rule.endpoint](**req.view_args)
    [Tue Sep 20 15:53:25.431798 2016] [wsgi:error] [pid 21070]   File "/var/www/tpa-tools/tpa_tools/__init__.py", line 72, in beehive_get_data
    [Tue Sep 20 15:53:25.431810 2016] [wsgi:error] [pid 21070]     csv_output += beehive_get_data_for_day_and_nodes(day_parsed, list_of_nodes)
    [Tue Sep 20 15:53:25.431830 2016] [wsgi:error] [pid 21070]   File "/var/www/tpa-tools/tpa_tools/__init__.py", line 109, in beehive_get_data_for_day_and_nodes
    [Tue Sep 20 15:53:25.431837 2016] [wsgi:error] [pid 21070]     objects, rawdata = pytdms.read("/mnt/wsn/" + day_of_log + ".tdms")
    [Tue Sep 20 15:53:25.431842 2016] [wsgi:error] [pid 21070]   File "/usr/local/lib/python3.4/site-packages/pytdms.py", line 621, in read
    [Tue Sep 20 15:53:25.431847 2016] [wsgi:error] [pid 21070]     data = readSegment(f,sz,data)
    [Tue Sep 20 15:53:25.431851 2016] [wsgi:error] [pid 21070]   File "/usr/local/lib/python3.4/site-packages/pytdms.py", line 520, in readSegment
    [Tue Sep 20 15:53:25.431857 2016] [wsgi:error] [pid 21070]     newdata = readRawData(f,leadin,newobjects,newobjectorder,filesize)
    [Tue Sep 20 15:53:25.431861 2016] [wsgi:error] [pid 21070]   File "/usr/local/lib/python3.4/site-packages/pytdms.py", line 443, in readRawData
    [Tue Sep 20 15:53:25.431866 2016] [wsgi:error] [pid 21070]     data[c] = array.array(tdsDataTypesTranscriptions[datatype])
    [Tue Sep 20 15:53:25.431877 2016] [wsgi:error] [pid 21070] ValueError: bad typecode (must be b, B, u, h, H, i, I, l, L, q, Q, f or d)
    [Tue Sep 20 15:53:25.431895 2016] [wsgi:error] [pid 21070] 

```

The relevant line of my code is this:

`objects, rawdata = pytdms.read("/mnt/wsn/" + day_of_log + ".tdms")
`

I tracked it down and realised that it had previously worked in pyTDMS 0.0.2 and now in 0.0.3 there is this line:

`data[c] = array.array(tdsDataTypesTranscriptions[datatype])
`
Which will throw an error for datatype 

`'tdsTypeTimeStamp'             :' ', # SHOULD BE HANDLED SEPARATELY
`

**Comment by petebachant** [comment]
To be honest, I'm not really maintaining this code very actively. Have you tried npTDMS? If you end up getting pyTDMS to work, please send a PR and I will gladly merge.
